<?php
// $Id: media_bitgravity.module,v 1.1.2.1 2010/09/23 21:04:55 aaron Exp $

/**
 *  @file media_bitgravity/media_bitgravity.module
 *  Embedded Video Field provider file for Bitgravity.com.
 */

/* ***************************************** */
/* INCLUDES                                  */
/* ***************************************** */

// A registry of variable_get defaults.
include_once('includes/media_bitgravity.variables.inc');

/**
 * Implementation of hook_menu().
 */
function media_bitgravity_menu() {
  return array(
    'admin/settings/media_bitgravity' => array(
      'title' => 'Media: Vimeo',
      'description' => 'Administer the Media: Vimeo module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('media_bitgravity_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/media_bitgravity.admin.inc',
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function media_bitgravity_theme($existing, $type, $theme, $path) {
  return array(
    'media_bitgravity' => array(
      'file' => 'media_bitgravity.theme.inc',
      'path' => $path .'/themes',
      'arguments' => array('video_code' => NULL, 'options' => array()),
      'template' => 'media-vimeo',
    ),
    'media_bitgravity_flash' => array(
      'file' => 'media_bitgravity.theme.inc',
      'path' => $path .'/themes',
      'arguments' => array('video_code' => NULL, 'options' => array()),
      'template' => 'media-vimeo-flash',
    ),
    'media_bitgravity_universal' => array(
      'file' => 'media_bitgravity.theme.inc',
      'path' => $path .'/themes',
      'arguments' => array('video_code' => NULL, 'options' => array()),
      'template' => 'media-vimeo-universal',
    ),
  );
}

/**
 * Implementation of hook_emfield_providers().
 */
function media_bitgravity_emfield_providers($module, $provider = NULL) {
  // We know this module only includes the main provider file, avoid needless
  // PHP warnings.
  if ($module == 'emvideo' && (!isset($provider) || ($provider == 'vimeo'))) {
    static $path;
    // Cache the result for later.
    if (!isset($path)) {
      $found = drupal_system_listing("$provider\.inc$", drupal_get_path('module', 'media_bitgravity') ."/includes/providers/$module", 'name', 0);
      if (is_array($found) && !empty($found)) {
        $path = $found;
      }
    }
    return $path;
  }
}
